// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jymgrlxabmzuzdfccuzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5bWdybHhhYm16dXpkZmNjdXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4ODQ2NzcsImV4cCI6MjA4NTQ2MDY3N30.ibvQ57dLadGd0avkHaw0NlzGQz1GU_EjWNrC8bB1Ld8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});